name: S3-cleanup

on: delete

env:
  bucket-name: 'dokka-snapshots'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials for S3 access
        uses: aws-actions/configure-aws-credentials@v1.5.9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Delete branch from s3
        run: aws s3 --recursive rm s3://${{ env.bucket-name }}/${{ github.event.ref }}
